### ISSUE TITLE
PDF inaccessible on mobiles

### ISSUE THREAD

**Issue by wezm** [carols10cents/rust-out-your-c-talk#1]
Following the link in the README to the PDF with speaker notes on a phone (iPhone 6s plus in this case) shows a GitHub page with the message, "This file is too big to show. Sorry!". Suggest linking to the raw file instead. 😊

**Comment by carols10cents** [comment]
I had no idea github would do that! Thanks for the tip, and sorry it took me so long to see this! Should be fixed now! ❤️
